global:
  scrape_interval: 15s
  external_labelse:
    monitor: "Scraper Monitor"

scrape_configs:
  # Prometheus monitor
  - job_name: "Prometheus"
    scrape_interval: "5s"
    static_configs:
      - targets: ["localhost:9090"]
  # os monitor
  - job_name: "node"
    scrape_interval: "10s"
    static_configs:
      - targets: ["localhost:9100"]